import path from 'path'

import { coverageConfigDefaults, defineConfig } from 'vitest/config'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: ['./src/test/setup.ts'],
    passWithNoTests: true,
    coverage: {
      reporter: ['text', 'lcov'],
      exclude: [
        // Keep Vitest's default exclusions (node_modules,
        // **/*.config.*, **/*.test.*, **/*.d.ts, etc.). Defining `exclude`
        // without these would replace them and pollute the coverage figures.
        ...coverageConfigDefaults.exclude,
        // Build configs not covered by Vitest's default list
        // (postcss, tailwind, etc.).
        '**/*.config.{js,cjs,mjs,ts}',
        // Testing infrastructure (MSW, render helpers).
        'src/test/**',
        // Entrypoint and app bootstrap/composition (wiring, not logic).
        'src/main.tsx',
        'src/app/**',
        // Barrels: only re-exports, no executable code of their own.
        'src/**/index.ts',
        // UI primitives generated by shadcn (third-party, not our own code).
        'src/shared/components/ui/**',
        // Type-only modules (no executable statements).
        'src/shared/types/**',
        'src/features/projects/types.ts',
        'src/features/dashboard/types.ts',
      ],
    },
  },
  resolve: {
    alias: { '@': path.resolve(__dirname, './src') },
  },
})
